export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const GOOGLE_SIGNIN_SUCCESS = "GOOGLE_SIGNIN_SUCCESS";
export const GOOGLE_SIGNIN_FAILURE = "GOOGLE_SIGNIN_FAILURE";

export const VERIFY_TOKEN_REQUEST = "VERIFY_TOKEN_REQUEST";
export const VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS";
export const VERIFY_TOKEN_FAILURE = "VERIFY_TOKEN_FAILURE";


export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";

export const GET_ALL_TODOS = "GET_ALL_TODOS";
export const GET_ALL_TODOS_SUCCESS = "GET_ALL_TODOS_SUCCESS";
export const GET_ALL_TODOS_FAILURE = "GET_ALL_TODOS_FAILURE";

export const MARK_COMPLETED = "MARK_COMPLETED";
export const MARK_COMPLETED_SUCCESS = "MARK_COMPLETED_SUCCESS";
export const MARK_COMPLETED_FAILURE = "MARK_COMPLETED_FAILURE";


export const DELETE_MULTIPLE = "DELETE_MULTIPLE";
export const DELETE_MULTIPLE_SUCCESS = "DELETE_MULTIPLE_SUCCESS";
export const DELETE_MULTIPLE_FAILURE = "DELETE_MULTIPLE_FAILURE";


export const DELETE_ONE = "DELETE_ONE";
export const DELETE_ONE_SUCCESS = "DELETE_ONE_SUCCESS";
export const DELETE_ONE_FAILURE = "DELETE_ONE_FAILURE";

export const UPDATE_TODO = "UPDATE_TODO";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_FAILURE = "UPDATE_TODO_FAILURE";
